#-------------------------------
# General Site Settings
title: eNanak
logo: "/images/logo.svg" # You can add own logo.
description: Pequeño espacio, gran sueño


#-------------------------------
# Author Settings
author:
  name: Daniel Proaño
  image: "/images/perfil.jpeg"
  say-hello: Hola, soy <strong>Daniel Proaño</strong>
  bio: Soy estudiante de Ciencias de la Computación con un enfoque en sistemas computacionales y tecnología. Me interesa profundamente la ciberseguridad y tengo habilidades analíticas para resolver problemas complejos. Me adapto rápidamente a nuevas tecnologías y destaco en la atención al detalle y la comunicación efectiva. Busco seguir desarrollándome en áreas de ciberseguridad y sistemas avanzados de computación.

#-------------------------------
# Contact links
twitter: https://x.com/eNanak869 # Add your Twitter handle
github: https://github.com/eNanak # Add your Facebook handle
gmail: lproanoc869@gmail.com # Add your Instagram handle
linkedin: https://www.linkedin.com/in/daniel-proa%C3%B1o-55356633b/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
